# Prometheus設定ファイル - ITマネジメントシステム本番環境

global:
  scrape_interval: 15s     # デフォルトのスクレイプ間隔
  evaluation_interval: 15s # デフォルトの評価間隔
  scrape_timeout: 10s      # スクレイプタイムアウト

# Alertmanagerの設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# アラートルールファイルのロード
rule_files:
  - "/etc/prometheus/alerts.yml"

# スクレイプ設定
scrape_configs:
  # Prometheusのself-monitoring設定
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # アプリケーションバックエンド
  - job_name: "backend"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["backend:5000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "backend"

  # フロントエンドアプリケーション
  - job_name: "frontend"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["frontend:3000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "frontend"

  # Nginxエクスポーター
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "nginx"

  # Node Exporter - ホストマシンのメトリクス
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "host"

  # SQLエクスポーター - データベースメトリクス
  - job_name: "sql_exporter"
    static_configs:
      - targets: ["sql-exporter:9399"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "database"

  # cAdvisor - コンテナメトリクス
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - source_labels: [container_name]
        regex: '.+'
        action: keep

  # Blackbox Exporter - 外部健全性チェック
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]  # HTTPチェックで2xxレスポンスを期待
    static_configs:
      - targets:
          - https://it-management.example.com   # フロントエンド
          - https://api.it-management.example.com/health  # バックエンドAPI
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox Exporterのアドレス

# リモートストレージの設定（オプション）
# remote_write:
#   - url: "https://remote-storage-service/api/v1/write"
#     basic_auth:
#       username: "remote_storage_user"
#       password: "remote_storage_password"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'go_.*'
#         action: drop

# リモート読み取りの設定（オプション）
# remote_read:
#   - url: "https://remote-storage-service/api/v1/read"
#     basic_auth:
#       username: "remote_storage_user"
#       password: "remote_storage_password"
#     read_recent: true